// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.3
// source: test2.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GrpcServer2_Test2_FullMethodName = "/server.GrpcServer2/Test2"
)

// GrpcServer2Client is the client API for GrpcServer2 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GrpcServer2Client interface {
	Test2(ctx context.Context, in *ReqMsg2, opts ...grpc.CallOption) (*RpMsg2, error)
}

type grpcServer2Client struct {
	cc grpc.ClientConnInterface
}

func NewGrpcServer2Client(cc grpc.ClientConnInterface) GrpcServer2Client {
	return &grpcServer2Client{cc}
}

func (c *grpcServer2Client) Test2(ctx context.Context, in *ReqMsg2, opts ...grpc.CallOption) (*RpMsg2, error) {
	out := new(RpMsg2)
	err := c.cc.Invoke(ctx, GrpcServer2_Test2_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcServer2Server is the server API for GrpcServer2 service.
// All implementations must embed UnimplementedGrpcServer2Server
// for forward compatibility
type GrpcServer2Server interface {
	Test2(context.Context, *ReqMsg2) (*RpMsg2, error)
	mustEmbedUnimplementedGrpcServer2Server()
}

// UnimplementedGrpcServer2Server must be embedded to have forward compatible implementations.
type UnimplementedGrpcServer2Server struct {
}

func (UnimplementedGrpcServer2Server) Test2(context.Context, *ReqMsg2) (*RpMsg2, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Test2 not implemented")
}
func (UnimplementedGrpcServer2Server) mustEmbedUnimplementedGrpcServer2Server() {}

// UnsafeGrpcServer2Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrpcServer2Server will
// result in compilation errors.
type UnsafeGrpcServer2Server interface {
	mustEmbedUnimplementedGrpcServer2Server()
}

func RegisterGrpcServer2Server(s grpc.ServiceRegistrar, srv GrpcServer2Server) {
	s.RegisterService(&GrpcServer2_ServiceDesc, srv)
}

func _GrpcServer2_Test2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqMsg2)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcServer2Server).Test2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrpcServer2_Test2_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcServer2Server).Test2(ctx, req.(*ReqMsg2))
	}
	return interceptor(ctx, in, info, handler)
}

// GrpcServer2_ServiceDesc is the grpc.ServiceDesc for GrpcServer2 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GrpcServer2_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "server.GrpcServer2",
	HandlerType: (*GrpcServer2Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Test2",
			Handler:    _GrpcServer2_Test2_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test2.proto",
}
