// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.3
// source: test.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GrpcServer_Test_FullMethodName = "/server.GrpcServer/Test"
)

// GrpcServerClient is the client API for GrpcServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GrpcServerClient interface {
	Test(ctx context.Context, in *ReqMsg, opts ...grpc.CallOption) (*RpMsg, error)
}

type grpcServerClient struct {
	cc grpc.ClientConnInterface
}

func NewGrpcServerClient(cc grpc.ClientConnInterface) GrpcServerClient {
	return &grpcServerClient{cc}
}

func (c *grpcServerClient) Test(ctx context.Context, in *ReqMsg, opts ...grpc.CallOption) (*RpMsg, error) {
	out := new(RpMsg)
	err := c.cc.Invoke(ctx, GrpcServer_Test_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcServerServer is the server API for GrpcServer service.
// All implementations must embed UnimplementedGrpcServerServer
// for forward compatibility
type GrpcServerServer interface {
	Test(context.Context, *ReqMsg) (*RpMsg, error)
	mustEmbedUnimplementedGrpcServerServer()
}

// UnimplementedGrpcServerServer must be embedded to have forward compatible implementations.
type UnimplementedGrpcServerServer struct {
}

func (UnimplementedGrpcServerServer) Test(context.Context, *ReqMsg) (*RpMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Test not implemented")
}
func (UnimplementedGrpcServerServer) mustEmbedUnimplementedGrpcServerServer() {}

// UnsafeGrpcServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrpcServerServer will
// result in compilation errors.
type UnsafeGrpcServerServer interface {
	mustEmbedUnimplementedGrpcServerServer()
}

func RegisterGrpcServerServer(s grpc.ServiceRegistrar, srv GrpcServerServer) {
	s.RegisterService(&GrpcServer_ServiceDesc, srv)
}

func _GrpcServer_Test_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcServerServer).Test(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrpcServer_Test_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcServerServer).Test(ctx, req.(*ReqMsg))
	}
	return interceptor(ctx, in, info, handler)
}

// GrpcServer_ServiceDesc is the grpc.ServiceDesc for GrpcServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GrpcServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "server.GrpcServer",
	HandlerType: (*GrpcServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Test",
			Handler:    _GrpcServer_Test_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test.proto",
}
