version: '3'
services:
  etcd:
    image: quay.io/coreos/etcd:v3.3.12
    container_name: etcd
    ports:
      - 23791:2379
      - 2380
    environment:
      ETCDCTL_API: 3
    #volumes:
    #  - ./data/etcd/etcd-data:/etcd-data
    networks:
      - mynet
    command:
      - "/usr/local/bin/etcd"
      - "--name"
      - "s1"
      - "--data-dir"
      - "/etcd-data"
      - "--advertise-client-urls"
      - "http://0.0.0.0:2379"
      - --listen-client-urls
      - "http://0.0.0.0:2379"
      - "--initial-advertise-peer-urls"
      - "http://0.0.0.0:2380"
      - "--listen-peer-urls"
      - "http://0.0.0.0:2380"
      - "--initial-cluster-token"
      - "tkn"
      - "--initial-cluster"
      - "s1=http://0.0.0.0:2380"
      - "--initial-cluster-state"
      - "new"
  etcdkeeper:
    image: deltaprojects/etcdkeeper
    container_name: etcdkeeper_single
    ports:
      - 8088:8080
    networks:
      - mynet
networks:
  mynet:
    external: true